track_folder: 'tracks'
elevation_data: 'out/design_elevation.csv'
metadata_file: 'out/design_stops.csv'
center_image_path: '../images/centerimage.png'
canvas_width: 1200
canvas_height: 1200
line_size: 4
line_color: 'white'
circle_radius: 200
start_angle: -90
padding_outside: 250
padding_inside: 50

font_family: 'Arial'
heading_text: 'Buen Camino'
heading_color: 'white'
heading_rotation: '60%'
footer_text: 'Test text'
footer_color: 'white'
footer_rotation: '25%'
stop_text_color: 'white'